### ISSUE TITLE
Invalid panda path in

### ISSUE THREAD

**Issue by philipdev** [cflavio/yorg#1]
Hi I have been looking into your code (learning panda myself),
and inorder to run i needed to change the path to a pandapath in imgbtn.py
e.g:
from panda3d.core import Filename

maps = loader.loadModel(Filename.fromOsSpecific(this_path) + '/../../assets/img_btn')

I think you can also load these against the working directory of panda  prefixed with models (or any other python path)

Nice work dooh,
Greetings

**Comment by lametta** [comment]
Hi Philip, thx for the test, we fix the problem soon.
Luca

**Comment by cflavio** [comment]
Hi philipdev! I can't replicate it: I have tried it with Panda3D 1.9.2 on Windows, OSX and Linux and it works without the correction you needed. Which version of Panda are you running? Thank you very much! :)

**Comment by cflavio** [comment]
Fixed, thank you very much for reporting it! :)
