### ISSUE TITLE
Missing front and rear wheels (egg files)

### ISSUE THREAD

**Issue by philipdev** [cflavio/yorg#2]
Cars themis and diones cars are missing frontwheel.egg and rearwheel.egg (files dont exist)

**Comment by lametta** [comment]
Hello Philip,
sorry for my English.
We know this problem.
It happens in the models of cars that have only one type of wheel object; Panda 3D search the front wheel and the rear wheel object, if it can't found, replaces the missing wheel(front or rear) with first object wheel it has loaded(front or rear) and warns that missing the second model.
Code have to fix.

Thx.
Luca
