### ISSUE TITLE
Yorg 0.10.0 failed on race start

### ISSUE THREAD

**Issue by Symbian9** [cflavio/yorg#22]
### Current behaviors

1. Launch *Yorg*;
2. Choose "Single race" mode;
3. Select the track;
4. Select the car;
5. Select driver;
6. Window show "LOADING.." screen for few seconds, then *Yorg* fully failed.

Here is full breakdown log:

- https://gist.github.com/Symbian9/8c6d70b14d946b095f89120da0e237ea

### System details

Yorg Version: `0.10.0` (binary build `yorg-0.10.0-linux_amd64` taken from itch.io page)

PC:

- OS: MX 17 Horizon x86_64 (aka Debian 9.x)
- Kernel: 4.15.0-1-amd64
- RAM: 1743MiB 
- DE: Xfce
- WM: Xfwm4
- CPU: Intel Pentium Dual T2330 (2) @ 1.600GHz
- GPU: AMD ATI Radeon Xpress 1250

**Comment by cflavio** [comment]
Hi! We have the same drivers and I can confirm that the game doesn't start using them. Anyway, it happens only with Panda3D 1.9's builds: it works when I build it with Panda3D 1.10. So, this issue will be automatically solved when they will release Panda3D 1.10 and I will build with it. As a temporary workaround, you may launch it from source. Thank you very much!

**Comment by Symbian9** [comment]
> it works when I build it with Panda3D 1.10. So, this issue will be automatically solved when they will release Panda3D 1.10 and I will build with it

Any deadline? Week? Month?

**Comment by rdb** [comment]
1.10 is planned to be released by the end of the year.  No promises, though.

**Comment by cflavio** [comment]
Hi! I have published the new release, so this should work now! Thanks!
