### ISSUE TITLE
Physics: make cars heavier

### ISSUE THREAD

**Issue by m1ga** [cflavio/yorg#25]
The game is already fun to play but I would prefer it if the cars are a bit heavier so they won't jump too far and won't flip over that easily. Would it be possible to adjust the weight/gravity so it feels a bit more like a car and not like a balloon :smile:

**Comment by cflavio** [comment]
Hi! I have published the new release. It contains several changes to the driving model, and it should improve the aspect referred by this issue. Thanks!
