### ISSUE TITLE
problems with running game in stable branch

### ISSUE THREAD

**Issue by consultit** [cflavio/yorg#26]
Hi, in my linux box (Debian stretch) I tried to follow [the instructions](http://www.ya2.it/pages/yorg_setup.html) but the game started to run only by changing these steps:
```
...
$ virtualenv --python=/usr/bin/python venv
...
$ pip install panda3d SCons psutil
...
```
bye

**Comment by cflavio** [comment]
Hi! Actually there was a misalignment between the instructions and the branches. Now I've copied the instructions in the readme file, so they can reflect the differences of the branches. Thank you very much for reporting that!
