### ISSUE TITLE
Fullscreen and AA options instant crash

### ISSUE THREAD

**Issue by LiamDawe** [cflavio/yorg#40]
Hi, nothing happens in terminal to show you but when trying to run fullscreen or turn on AA the entire game just quits.

Let me know how I can show info.

**Comment by cflavio** [comment]
Hi! Thank you for reporting this! Unfortunately, I can't replicate the issue. There should be this file: ~/.local/share/Yorg/p3d_log.log; could you send it to me, please? Thank you very much!

**Comment by LiamDawe** [comment]
Weird, can't reproduce it now. Closing until it happens...
