### ISSUE TITLE
Shader errors with Panda3D without proprietary Cg support

### ISSUE THREAD

**Issue by akien-mga** [cflavio/yorg#5]
I've built the Panda3D SDK 1.9.4 without support for the NVIDIA Cg technology, as I want to package Panda3D for my distro as a libre engine and can therefore not rely on proprietary libraries.

Apparently the game expects Cg support though, as the console is spammed with this error while playing:
```
:shader(error): Support for Cg shaders is not enabled.
```

It would be nice to detect if Cg shaders are available and prevent trying to use them if not, to avoid the spam. Ideally, having a libre alternative for those shaders would be great.

----

System info:
```
:ya2: 19:22:32 version: source
:ya2: 19:22:32 operative system: Linux 4.9.35-desktop-1.mga6 #1 SMP Thu Jun 29 19:27:27 UTC 2017
:ya2: 19:22:32 architecture: ('64bit', 'ELF')
:ya2: 19:22:32 machine: x86_64
:ya2: 19:22:32 platform: Linux-4.9.35-desktop-1.mga6-x86_64-with-mageia-6-Cauldron
:ya2: 19:22:32 processor: x86_64
:ya2: 19:22:32 cores: 4
:ya2: 19:22:32 panda version: 1.9.4 
:ya2: 19:22:32 bullet version: 286
:ya2: 19:22:32 appdata: /home/akien
:ya2: 19:22:32 NVIDIA Corporation
:ya2: 19:22:32 GeForce GTX 670MX/PCIe/SSE2
:ya2: 19:22:32 shader: 4.50
:ya2: 19:22:32 4.5.0 NVIDIA 375.66
:ya2: 19:22:32 driver version: 4.5
:ya2: 19:22:32 fullscreen: False
:ya2: 19:22:32 resolution: 1280x720
```

**Comment by cflavio** [comment]
I started implementing GLSL [shaders](https://github.com/cflavio/yyagl/tree/master/assets/shaders), but they're still unfinished, unpolished and bugged. Anyway, I should wait for Panda3D 1.10 since shaders' support has been improved a lot into that version. So, yes, the mid-term plan is to migrate. :)
